# Generated by Django 4.1.7 on 2023-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотографие книги')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('genre', models.CharField(choices=[('FANTASTIC', 'ФАНТАСТИКА'), ('HORROR', 'ХОРОР'), ('ROMANCE', 'РОМАНТИКА'), ('COMEDY', 'КОМЕДИЯ'), ('NOVEL', 'НОВЕЛЛА'), ('DETECTIVE', 'ДЕТЕКТИВ')], max_length=100)),
                ('video', models.URLField()),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Цена книги')),
            ],
        ),
    ]
