# Generated by Django 4.1.7 on 2023-02-17 15:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='create_date',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FANTASTIC', 'ФАНТАСТИКА'), ('HORROR', 'ХОРОР'), ('ROMANCE', 'РОМАНТИКА'), ('COMEDY', 'КОМЕДИЯ'), ('NOVEL', 'НОВЕЛЛА'), ('DETECTIVE', 'ДЕТЕКТИВ')], default=datetime.datetime(2023, 2, 17, 15, 30, 33, 156205, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=datetime.datetime(2023, 2, 17, 15, 30, 46, 346079, tzinfo=datetime.timezone.utc), verbose_name='Колличество книг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фотографие книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
    ]
